### ISSUE TITLE
Resolving keyness#keyness;0.1-SNAPSHOT ... module not found

### ISSUE THREAD

**Issue by mazlo** [HPI-Information-Systems/ProLOD#40]
Dear ProLOD developers,

I am trying to run ProLOD with `sbt "project prolod_play" run`, but it cannot start because of a missing dependency. 

```sh
$ sbt "project prolod_play" clean run
[info] Loading project definition from H:\git\ProLOD\project
[info] Set current project to ProLOD++ (in build file:/H:/git/ProLOD/)
[info] Set current project to prolod-play (in build file:/H:/git/ProLOD/)
[success] Total time: 0 s, completed 16.10.2018 16:21:41
[info] Updating {file:/H:/git/ProLOD/}prolod_common...
[info] Resolving keyness#keyness;0.1-SNAPSHOT ...
[warn]  module not found: keyness#keyness;0.1-SNAPSHOT
[warn] ==== local: tried
[warn]   C:\Users\user\.ivy2\local\keyness\keyness\0.1-SNAPSHOT\ivys\ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\user\.sbt\preloaded\keyness\keyness\0.1-SNAPSHOT\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/user/.sbt/preloaded/keyness/keyness/0.1-SNAPSHOT/keyness-0.1-SNAPSHOT.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/keyness/keyness/0.1-SNAPSHOT/keyness-0.1-SNAPSHOT.pom
[warn] ==== Typesafe Releases: tried
[warn]   http://repo.typesafe.com/typesafe/maven-releases/keyness/keyness/0.1-SNAPSHOT/keyness-0.1-SNAPSHOT.pom
[warn] ==== Maven2 Local: tried
[warn]   file:/C:/Users/user/.m2/repository/keyness/keyness/0.1-SNAPSHOT/keyness-0.1-SNAPSHOT.pom
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: keyness#keyness;0.1-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          keyness:keyness:0.1-SNAPSHOT (H:\git\ProLOD\prolod-common\build.sbt#L6-20)
[warn]            +- prolod-common:prolod-common_2.11:0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: keyness#keyness;0.1-SNAPSHOT: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
```

I already managed to clone [graphlod](https://github.com/anjeve/graphlod) and build it, but I don't know how to proceed with this error. Any ideas?

**Comment by xchrdw** [comment]
The keyness repository is available here: https://github.com/anjeve/keyness
I think you have to "mvn install" it. Could you try that?

**Comment by mazlo** [comment]
Ah thank you, it works! At least I can compile and start. 

People need to clone this project and two additional projects 

https://github.com/anjeve/graphlod.git
https://github.com/anjeve/keyness

and `mvn install` both.
