### ISSUE TITLE
Required database and configuration

### ISSUE THREAD

**Issue by mazlo** [HPI-Information-Systems/ProLOD#41]
I managed to start the application and I can see something on `http://localhost:9000/#/`. But I cannot use it and in parallel I see an exception on the command line, which says that some configuration is missing.

```bash
[info] Compiling 16 Scala sources and 1 Java source to H:\git\ProLOD\prolod-play\target\scala-2.11\classes...
[info] play.api.Play - Application started (Dev)
[error] application -

! @79ice7l7l - Internal server error, for (GET) [/server/datasets] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[Missing: No configuration setting found for key 'db.db2']]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.3.jar:2.4.3]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.3.jar:2.4.3]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.3.jar:2.4.3]
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.3.jar:2.4.3]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.3.jar:2.4.3]
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'db.db2'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152) ~[config-1.3.0.jar:na]
        at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145) ~[config-1.3.0.jar:na]
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172) ~[config-1.3.0.jar:na]
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176) ~[config-1.3.0.jar:na]
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184) ~[config-1.3.0.jar:na]
```

My `prolod-play/conf/database.conf` file says

```properties
db.default.driver=org.h2.Driver
db.default.url="jdbc:h2:mem:play"
db.default.user=sa
db.default.password=""
db.mainSchema=datasets
db.defaultUserView=graphstatistics
```

Do I really need the db2 to use the application? I would rather like to go with a mysql..

**Comment by xchrdw** [comment]
This was mostly developed on db2. It should be possible to change to mysql, but we might have used db2 specific sql syntax and configurations that need to be fixed. 
These are good places to start:
https://github.com/HPI-Information-Systems/ProLOD/search?q=db.db2&unscoped_q=db.db2
